#+title: Handle Connection

* Translating from C++ to Ivy

Here we try to take the function ~handle_connection~ and translate it from C++ into Ivy. This first presentation of it is partially written by hand. After furhter inspection, we parse this out into a couple versions of the code. One where a server stores a single connected variable, and another where a server represents this data as a set via the STL.

This first section is using the single connected variable, however our analysis in Ivy is more akin to how we imagine functions would be handled.

This section is about this hybrid approach. Elanor will handle the ~int~ variable/function case. And later I will handle the set-based case.

** Safety
The safety property we want to keep in mind here is that servers are connected to a maximum of one client. That is, in Ivy,
#+begin_src ivy
invariant forall C1 : client . forall C2 : client . forall S : server . connected(S,C1) & connected(S,C2) -> C1 = C2
#+end_src
** C++ Source
#+BEGIN_SRC C++
int handle_connection(int connectionfd) {
	char msg[MAX_MESSAGE_SIZE + 1];
	memset(msg, 0, sizeof(msg));

	size_t recvd = 0;
	ssize_t rval;

    rval = recv(connectionfd, msg + recvd, MAX_MESSAGE_SIZE - recvd, 0);
	if (rval == -1) {
		return -1;
    }
    recvd += rval;
    rval = recv(connectionfd, msg + recvd, MAX_MESSAGE_SIZE - recvd, 0);
    if (rval != 0) {
        return -1;
    }

    char * command = strtok(msg, " ");
    int client_id = atoi(strtok(NULL, " "));

    if (strcmp(command, "connect") == 0) {
        if (SEMAPHORE) {
            SEMAPHORE = false;
            connected = client_id;
        } else {
          return -1;
        }
   }
    if (strcmp(command, "disconnect") == 0) {
        // command = disconnect
        if (connected == client_id) {
            connected = -1;
            SEMAPHORE = true;
        }
        else {
          return -1;
        }
    }
	close(connectionfd);
	return 0;
}
#+END_SRC

Note, for simplifying the core of this translation, from this code we have already removed unnecessary lines involving print statements and raising descriptive errors. In any sort of mechanical process, we would toss these out as extraneous information anyway.

** Some Print Statements May Be Useful

This might prove problematic if the print statement contained semantically useful information related to the desired specification. However, in these cases we can enforce that the source code use a reserved printing function to distinguish these from extraneous prints.

That is, we may use some ~log()~ function to represent meaningful prints whose calls should not be elided, and continue using ~printf()~ for ones we may freely toss out. Likewise, we will have the user distinguish important error messages/side effects from unimportant ones.

** Networking
*** Form of the socket code
We are assuming that all of the network code is handled on the server side to boil down to a simple ~pending_message~ predicate in Ivy.

A first pass at this assume that all the message passing we perform in C++ takes on the same form of socket logic, and thus we only reason about this sort of style once up front. This does not generalize to all C++ programs by any means, but for verification purposes we may think of this as providing a trusted library/API used for sending/receiving messages.

In particular, we assume that we see this same pattern,
#+begin_src C++
size_t recvd = 0;
ssize_t rval;

rval = recv(connectionfd, msg + recvd, MAX_MESSAGE_SIZE - recvd, 0);
if (rval == -1) {
	return -1;
}
recvd += rval;
rval = recv(connectionfd, msg + recvd, MAX_MESSAGE_SIZE - recvd, 0);
if (rval != 0) {
    return -1;
}

char * command = strtok(msg, " ");
int client_id = atoi(strtok(NULL, " "));
#+end_src

*** Decoding the message
All but the final two lines deal with receiving the message. We assume that the message is shorter than ~MAX_MESSAGE_SIZE~. If so, and there are no errors, then the string ~msg~ holds the intended message.

If there are any errors receiving this message, we short circuit and return -1.

The final two lines deal with decoding the message (handled as a space-delimited string). We may think of this as ~strtok(msg, " ")~ as being a primitive notion of "get first index of message". Then ~strtok(NULL, " ")~ we may treat as another primitive that gets the next part of the message, and we must be careful to call this the correct number of times. Note we use ~atoi~ to cast the string to the proper type.

We aren't assuming any corruption of the messages, only arbitrary delays. So, I don't think it is particular useful or interesting at the moment to verify correct decoding this message. If the developer promises to send a three argument space-delimited string such that everything is well-formatted, I'm willing to take their word that they did this encoding properly.

** Declarations Used in Ivy
We have made some pretty strict assumptions on the syntax used for our socket code, but they seem reasonably fair at first glance. We might need the user to provide type annotations for the message parameters, or we can likely infer them from how the message is decoded (assuming that the message decoding process is also in a similar format)

Once we have isolated the parameters of the message --- here, ~command~ and ~client_id~ --- we can use these to define some types in Ivy representing the same variables. We can further use these to define what the ~pending_message~ type in Ivy should be.

#+begin_src ivy
type client
type server
type command = {connect,disconnect,other}
relation pending_message(X:client,Y:server,Z:command)
#+end_src

Each of client, server, and command get their own type.

*** Command as an enumerated type
Through a symbolic analysis we can likely determine that the command variable takes on one of three cases
1. the string literal ~"connect"~
2. the string literal ~"disconnect"~
3. anything else

This sort of analysis looks is based on usage of the variable, particularly in conditionals.

I have not actually ran such an analysis; however, I am confident that it can be done. This sort of thing is done when analyzing code paths in symbolic execution, such as in KLEE. So I'm fairly sure we could find some library code that does this for us in C++. If not, the methodology is out there for us to homebrew this if needed.

For this code in particular, we only apply this symbolic analysis to ~command~ in an ad-hoc way, because we glanced at it and assumed it was needed. However, more generally we probably want to do this sort of path case analysis for every variable that we transport from C++ into Ivy. In this example it just turns out that these symbolic paths are trivial for the ~client_id~ variable.

*** Pending Message Type
The pending message depends on the two variables in the message, ~command~ and ~client_id~. Further, this is a distributed system. Each server is running a copy of the given code, and this message should then be linked to whichever particular server received the message in question.

Here we are assuming we have access to this server's ID for free. In reality this either needs to be interalized into the C++ code, perhaps through a command line arg or environment variable, or internalized into the message. Our initial code did neither of these, but we can imagine adding these.

*** Semaphore and Connected
~semaphore~ is a boolean stored on each server, so we just make that a relation in Ivy.

~connected~ is a little stranger. In the C++ code, it appears to be a function that associates a client to each server. As each server stores the unique client it is connected to (reserving -1 to be a sentinel for no connection)
#+begin_src ivy
relation semaphore(s : server)
function connected(S : server) : client
#+end_src

However, if this is actually a function, then we get our desired safety property for free. In fact, we can't even state it as initally presented. And it isn't even clear how to state the property in a language where ~connected~ has type ~server -> client~

This is because by definition functions have unique outputs for a given input.

Because of this, I by hand relax this to a relation. However, this isn't really justified and is probably too influenced by what I already know to be an Ivy program describing this protocol.

#+begin_src
relation connected(S : server, C : client)
#+end_src

Without having a satisfying translation of this particular part, I feel very unclear on where we go from here. This part of the translation defines THE predicate crucial to understanding (and even stating) our invariant, and it is done by hand without any major mechanical motivation.

Perhaps the solution here is to make everything a relation a priori. Even though the C++ source makes it clear that every server is associated to a unique client (via the fact that the ~connected~ variable stores exactly one value), when moving into Ivy it may make sense to treat this as a binary relation between clients and servers. In reality this relation just so happens to reduce to a function, but up front we don't know that. And the safety property is ultimately about proving this fact.
** Initial State
We assume that no servers are connected to any clients when this system begins.
#+begin_src ivy
after init {
    semaphore(S) := true;
    # connected(S,C) := false;
    connected(S) := negative_one;
}
#+end_src
** ~handle_connection~ Action
We take the ~pending_message~ as a precondition to an action that represents the rest of the ~handle_connection~ function as given in C++. This is justified, as we reach this part of the code only if we have successfuly read a message from the socket.

The rest of this function is very simple and is nearly syntactically the same in Ivy
#+begin_src ivy
 action handle_connection (clientid : client, receiver : server, com : command) = {
    require pending_message(clientid, receiver, com);

    if (com = connect) {
       semaphore(receiver) := false;
       connected(receiver,  clientid) := true;
    }
    if (com = disconnect) {
       connected(receiver, clientid) := false;
       semaphore(receiver) := true;
    }
    pending_message(clientid, receiver, com) := false;
}
#+end_src

Another part of this that is done by hand is the updates to ~connected~. In C++ these are ~int~ assignments. It is not immediately clear how these affect the truth values of the predicates we have settled on.

My working assumption is that this "everything is a relation" attitude works. We say that each server is related the current values of its global/local variables at any give point in time.

Concretely, that means that when the server's copy of ~connected~ stores the value ~client_id~ we mark ~connected(server, client)~ to be true. Whenever we change this server's copy of ~connected~ we make this predicate false.

How we handle these predicates upon updating ~connected~ to -1 is not entirely justified and is done by hand for now. If we follow our relation analogy completely, it would be fair to make ~connected(reciever, client_id) := false~ after updating ~connected~ to -1; however, by our own rules we should also update ~connected(receiver, -1)~ to true.

We know as humans that this null connection to the "-1"-st client actually represents no connection at all. However in Ivy it isn't clear how we actually handle this without having user input explicitly noting that -1 is a special value.

This is also ignoring Ivy syntactic issues. "-1" does not exist in Ivy because "-" is not defined for free, and ~int~ do not exist for free either. We can choose to interpret ~client~ as the ~int~ type
#+begin_src ivy
type client
interpret client -> int
#+end_src
After reading some light Ivy documentation, I believe this means that Ivy has a built in theory of ~int~ and it adds axioms stating that ~client~ is a model of that theory. This does not handle the case of integer literals that we may or may not want to use. So we can also define a special client that is meant to represent the value of -1 (as stored in the ~connected~ variable) in Ivy
#+begin_src
individual negative_one : client
...
connected(receiver, clientid) := false;
connected(receiver, negative_one) := true
...
#+end_src

If we do add this ~negative_one~, we would also need to add some reasoning that sets ~connected(server, negative_one)~ to false at the appropriate time. This would likely be in the connect logic, but this is very done-by-hand right now and not clear how to generalize

*** Handle Connection with ~negative_one~ source
#+begin_src
action handle_connection (clientid : client, receiver : server, com : command) = {
    require pending_message(clientid, receiver, com);

    if (com = connect) {
       semaphore(receiver) := false;
       connected(receiver,  clientid) := true;
       connected(receiver,  negative_one) := false;
    }
    if (com = disconnect) {
       connected(receiver, clientid) := false;
       connected(receiver, negative_one) := true;
       semaphore(receiver) := true;
    }
    pending_message(clientid, receiver, com) := false;
}
#+end_src

** Ivy Source
Putting everything together
#+begin_src
#lang ivy1.7

type client

# interpret client -> int
individual negative_one : client

type server
type command = {connect,disconnect,other}

relation pending_message(X:client,Y:server,Z:command)
relation semaphore(S : server)
relation connected(S : server, C : client)

after init {
    semaphore(S) := true;
    connected(S,C) := false;
    connected(S) := negative_one;
}

action handle_connection (clientid : client, receiver : server, com : command) = {
    require pending_message(clientid, receiver, com);

    if (com = connect) {
       semaphore(receiver) := false;
       connected(receiver,  clientid) := true;
       connected(receiver,  negative_one) := false;
    }
    if (com = disconnect) {
       connected(receiver, clientid) := false;
       connected(receiver, negative_one) := true;
       semaphore(receiver) := true;
    }
    pending_message(clientid, receiver, com) := false;
}

action send_message (clientid : client, receiver : server, com : command) = {
    pending_message(clientid, receiver, com) := true;
}

export handle_connection

invariant forall C1 : client . forall C2 : client . forall S : server . (connected(S,C1) & connected(S,C2)) -> (C1 = C2)
#+end_src
* Set-based View
**  Source Code
#+begin_src C++
#include <arpa/inet.h>		// htons()
#include <stdio.h>		// printf(), perror()i
#include <string>
#include <stdlib.h>		// atoi()
#include <sys/socket.h>		// socket(), bind(), listen(), accept(), send(), recv()
#include <unistd.h>		// close()
#include <set>

#include "helpers.h"		// make_server_sockaddr(), get_port_number()

static const size_t MAX_MESSAGE_SIZE = 256;

bool SEMAPHORE = true;
std::set <int> connections;

int handle_connection(int connectionfd) {
	char msg[MAX_MESSAGE_SIZE + 1];
	memset(msg, 0, sizeof(msg));

	size_t recvd = 0;
	ssize_t rval;
	do {
		rval = recv(connectionfd, msg + recvd, MAX_MESSAGE_SIZE - recvd, 0);
		if (rval == -1) {
			return -1;
		}
		recvd += rval;
	} while (rval > 0);  // recv() returns 0 when client closes

    char * command = strtok(msg, " ");
    int client_id = atoi(strtok(NULL, " "));

    if (strcmp(command, "connect") == 0) {
        if (SEMAPHORE) {
            SEMAPHORE = false;
            connections.insert(client_id);
        } else {
          return -1;j
        }
    }
    if (strcmp(command, "disconnect") == 0) {
        if (connections.find(client_id) != connections.end()) {
            connections.erase(client_id);
            SEMAPHORE = true;
        }
        else {
          return -1;
        }
    }
	close(connectionfd);

	return 0;
}

/**
 ,* Endlessly runs a server that listens for connections and serves
 ,* them _synchronously_.
 ,*
 ,* Parameters:
 ,*		port: 		The port on which to listen for incoming connections.
 ,*		queue_size: 	Size of the listen() queue
 ,* Returns:
 ,*		-1 on failure, does not return on success.
 ,*/
int run_server(int port, int queue_size) {

	// (1) Create socket
	int sockfd = socket(AF_INET, SOCK_STREAM, 0);
	if (sockfd == -1) {
		perror("Error opening stream socket");
		return -1;
	}

	// (2) Set the "reuse port" socket option
	int yesval = 1;
	if (setsockopt(sockfd, SOL_SOCKET, SO_REUSEADDR, &yesval, sizeof(yesval)) == -1) {
		perror("Error setting socket options");
		return -1;
	}

	// (3) Create a sockaddr_in struct for the proper port and bind() to it.
	struct sockaddr_in addr;
	if (make_server_sockaddr(&addr, port) == -1) {
		return -1;
	}

	// (3b) Bind to the port.
	if (bind(sockfd, (sockaddr *) &addr, sizeof(addr)) == -1) {
		perror("Error binding stream socket");
		return -1;
	}

	// (3c) Detect which port was chosen.
	port = get_port_number(sockfd);
	printf("Server listening on port %d...\n", port);

	// (4) Begin listening for incoming connections.
	listen(sockfd, queue_size);

	// (5) Serve incoming connections one by one forever.
	while (true) {
		int connectionfd = accept(sockfd, 0, 0);
		if (connectionfd == -1) {
			perror("Error accepting connection");
			return -1;
		}

		if (handle_connection(connectionfd) == -1) {
			return -1;
		}
	}
}

int main(int argc, const char **argv) {
	// Parse command line arguments
	if (argc != 2) {
		printf("Usage: ./server port_num\n");
		return 1;
	}
	int port = atoi(argv[1]);

	if (run_server(port, 10) == -1) {
		return 1;
	}
	return 0;
}
#+end_src
** Ivy
#+begin_src ivy
 #lang ivy1.7

type client
type server
type command = {connect,disconnect,other}

relation pending_message(X:client,Y:server,Z:command)
relation semaphore(S : server)
relation connected(S : server, C : client)

after init {
    semaphore(S) := true;
    connected(S,C) := false;
}

action handle_connection (clientid : client, receiver : server, com : command) = {
    require pending_message(clientid, receiver, com);

    if (com = connect) {
       if (semaphore(receiver)) {
          semaphore(receiver) := false;
          connected(receiver,  clientid) := true;
       }
    }
    if (com = disconnect) {
       if (connected(receiver, clientid)) {
           connected(receiver, clientid) := false;
           semaphore(receiver) := true;
        }
    }
    pending_message(clientid, receiver, com) := false;
}

action send_message (clientid : client, receiver : server, com : command) = {
    pending_message(clientid, receiver, com) := true;
}

export handle_connection

invariant [strengthening_assertion] forall S : server . forall C : client . semaphore(S) -> ~connected(S,C)
invariant [safety] forall C1 : client . forall C2 : client . forall S : server . (connected(S,C1) & connected(S,C2)) -> (C1 = C2)

#+end_src
** Reasoning
Here we are using ~stl::set~ to represent which clients we are connected to, even though we ever only connect to one client in reality.

On the predicate side we are implicitly using the fact that sets over a type are viewable as maps into the booleans. This allows us to introduce the connected type as a map ~server -> client -> bool~ (or put another way, a relation over ~server~ and ~client~).

This sort of reasoning needs to be justified, but this seems to be something that can be done once and for all on the ~stl::set~ containers (polymorphic wrt to the type stored). That is, we verify the templated library code once up front, and may isntantiate it on this example to reason that set variables at each server must be tranlsated into Ivy as a relation between the server and each value witnessed in its set.

** Results
Given an appropriate strenghtening assertion (which I'm nearly positive is findable by I4 and/or IC3PO), we are able to prove the desired safety property.
#+begin_src
invariant [strengthening_assertion] forall S : server . forall C : client . semaphore(S) -> ~connected(S,C)
invariant [safety] forall C1 : client . forall C2 : client . forall S : server . (connected(S,C1) & connected(S,C2)) -> (C1 = C2)
#+end_src

This sort of analysis mirrors exactly the work with the abstract lock server performed by IC3PO.
* Variable-based View
** Source Code
#+begin_src C++
static const size_t MAX_MESSAGE_SIZE = 256;

bool semaphore = true;
int connected = -1;
// TODO: reflect internally the server ids. prob as a command line arg in main function

int handle_connection(int connectionfd) {
	char msg[MAX_MESSAGE_SIZE + 1];
	memset(msg, 0, sizeof(msg));

	size_t recvd = 0;
	ssize_t rval;

    rval = recv(connectionfd, msg + recvd, MAX_MESSAGE_SIZE - recvd, 0);
	if (rval == -1) {
		return -1;
    }
    recvd += rval;
    rval = recv(connectionfd, msg + recvd, MAX_MESSAGE_SIZE - recvd, 0);
    if (rval != 0) {
        return -1;
    }

    char * command = strtok(msg, " ");
    int client_id = atoi(strtok(NULL, " "));

    if (strcmp(command, "connect") == 0) {
        if (semaphore) {
            semaphore = false;
            connected = client_id;
        } else {
          return -1;
        }
   }
    if (strcmp(command, "disconnect") == 0) {
        if (connected == client_id) {
            connected = -1;
            semaphore = true;
        }
        else {
          return -1;
        }
    }
	close(connectionfd);
	return 0;
}
#+end_src
** Ivy
#+begin_src ivy
#lang ivy1.7

type client
individual negative_one : client

type server
type command = {connect,disconnect,other}

relation pending_message(X:client,Y:server,Z:command)

function semaphore(S : server) : bool
function connected(S : server) : client

after init {
    semaphore(S) := true;
    connected(S) := negative_one;
}

action handle_connection (clientid : client, receiver : server, com : command) = {
    require pending_message(clientid, receiver, com);
    if (com = connect) {
       if (semaphore(receiver) = true) {
          semaphore(receiver) := false;
          connected(receiver) := clientid;
       }
    }
    if (com = disconnect) {
       if (connected(receiver) = clientid) {
           connected(receiver) := negative_one;
           semaphore(receiver) := true;
        }
    }
    pending_message(clientid, receiver, com) := false;
}

action send_message (clientid : client, receiver : server, com : command) = {
    pending_message(clientid, receiver, com) := true;
}

export handle_connection


invariant [safety] forall C1 : client . forall C2 : client . forall S : server . (connected(S) = C1 & connected(S) = C2) -> (C1 = C2)

#+end_src
** Results
The invariant follows "for free" because functions have unique outputs.
#+begin_src
invariant [safety] forall C1 : client . forall C2 : client . forall S : server . (connected(S) = C1 & connected(S) = C2) -> (C1 = C2)
#+end_src

We justify translating this into a ~function~ in Ivy, because we take the point of view that for each variable of the server we have a function from servers to the type of that variable. That is, here we have a function ~server -> bool~ for ~semaphore~ and a function ~server -> client~ (maybe to ~int~) for the ~connected~ variable.
