type client 2
type server 2

relation link(X: client, Y: server)
relation semaphore(X: server)

# for y:server {
#     semaphore(y) := forall x. link(x, y);
# }

# for y:server {
#     semaphore(y) := true;
#     for x:client {
#         link(x, y) := false;
#     }
# }

# link(client1, server1) := true;
# semaphore(server1) := false;

# link(client1, server1) := false;
# semaphore(server1) := true;




